//* Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_START = 'LOGIN_START'

//* Error
export const ERROR = 'ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'

//* Notification
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW'
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE'

//* Users
export const GET_ALL_USER_START = 'GET_ALL_USER_START'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const CREATE_NEW_USER_START = 'CREATE_NEW_USER_START'
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS'
export const GET_USER_DATA_START = 'GET_USER_DATA_START'
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS'
export const UPDATE_USER_DATA_START = 'UPDATE_USER_DATA_START'
export const UPDATE_USER_DATA_SUCCESS = 'UPDATE_USER_DATA_SUCCESS'
export const SEND_NEW_CREDENTIALS_START = 'SEND_NEW_CREDENTIALS_START'
export const SEND_NEW_CREDENTIALS_SUCCESS = 'SEND_NEW_CREDENTIALS_SUCCESS'

//* Support
export const GET_SUPPORT_MESSAGES_START = 'GET_SUPPORT_MESSAGES_START'
export const GET_SUPPORT_MESSAGES_SUCCESS = 'GET_SUPPORT_MESSAGES_SUCCESS'
export const GET_ONE_SUPPORT_MESSAGE_START = 'GET_ONE_SUPPORT_MESSAGE_START'
export const GET_ONE_SUPPORT_MESSAGE_SUCCESS = 'GET_ONE_SUPPORT_MESSAGE_SUCCESS'


//* Packages
export const GET_ALL_PACKAGES_START = 'GET_ALL_PACKAGES_START'
export const GET_ALL_PACKAGES_SUCCESS = 'GET_ALL_PACKAGES_SUCCESS'
export const GET_PACKAGE_DATA_START = 'GET_PACKAGE_DATA_START'
export const GET_PACKAGE_DATA_SUCCESS = 'GET_PACKAGE_DATA_SUCCESS'
export const UPDATE_PACKAGE_DATA_START = 'UPDATE_PACKAGE_DATA_START'
export const UPDATE_PACKAGE_DATA_SUCCESS = 'UPDATE_PACKAGE_DATA_SUCCESS'
